# Admin User Me /sales/admin/auth/me
sandbox_sales_admin_api_auth_me:
    resource: "@SandboxSalesApiBundle/Controller/Auth/AdminAuthController.php"
    type:     annotation
    prefix:   /admin/auth

# Admin Rooms /sales/admin/buildings
sandbox_sales_admin_building:
    resource: "@SandboxSalesApiBundle/Controller/Building/AdminBuildingController.php"
    type:     annotation
    prefix:   /admin

# Admin Rooms /sales/admin/rooms/supplies
sandbox_sales_admin_room_supplies:
    resource: "@SandboxSalesApiBundle/Controller/Room/AdminRoomSuppliesController.php"
    type:     annotation
    prefix:   /admin

# Admin Rooms /sales/admin/rooms/attachments
sandbox_sales_admin_room_attachment:
    resource: "@SandboxSalesApiBundle/Controller/Room/AdminRoomAttachmentController.php"
    type:     annotation
    prefix:   /admin

# Admin Rooms /sales/admin/rooms
sandbox_sales_admin_room:
    resource: "@SandboxSalesApiBundle/Controller/Room/AdminRoomController.php"
    type:     annotation
    prefix:   /admin

# Admin Product /sales/admin/products/recommend
sandbox_sales_admin_products_recommend:
    resource: "@SandboxSalesApiBundle/Controller/Product/AdminProductRecommendController.php"
    type:     annotation
    prefix:   /admin

# Admin Product /sales/admin/products
sandbox_sales_admin_products:
    resource: "@SandboxSalesApiBundle/Controller/Product/AdminProductController.php"
    type:     annotation
    prefix:   /admin

# Admin Order /sales/admin/orders
sandbox_sales_admin_orders:
    resource: "@SandboxSalesApiBundle/Controller/Order/AdminOrderController.php"
    type:     annotation
    prefix:   /admin

# Admin User /sales/admin/users
sandbox_sales_admin_users:
    resource: "@SandboxSalesApiBundle/Controller/User/AdminUsersController.php"
    type:     annotation
    prefix:   /admin

# Admin Door /sales/admin/doors
sandbox_sales_admin_doors:
    resource: "@SandboxSalesApiBundle/Controller/Door/AdminDoorController.php"
    type:     annotation
    prefix:   /admin

# Admin Door /sales/admin/shops
sandbox_sales_admin_shops:
    resource: "@SandboxSalesApiBundle/Controller/Shop/AdminShopController.php"
    type:     annotation
    prefix:   /admin

# Admin Events Orders
sandbox_sales_admin_api_events_orders:
    resource: "@SandboxSalesApiBundle/Controller/Event/AdminEventOrderController.php"
    type:     annotation
    prefix:   /admin

# Admin Events Registrations
sandbox_sales_admin_api_events_registrations:
    resource: "@SandboxSalesApiBundle/Controller/Event/AdminEventRegistrationController.php"
    type:     annotation
    prefix:   /admin

# Events /sales/admin/events/{id}/comments
sandbox_sales_admin_api_event_comments:
    resource: "@SandboxSalesApiBundle/Controller/Event/AdminEventCommentController.php"
    type:     annotation
    prefix:   /admin

# Admin Events /sales/admin/events
sandbox_sales_admin_api_events:
    resource: "@SandboxSalesApiBundle/Controller/Event/AdminEventController.php"
    type:     annotation
    prefix:   /admin

# Location /sales/admin/location
sandbox_admin_api_location:
    resource: "@SandboxSalesApiBundle/Controller/Location/AdminLocationController.php"
    type:     annotation
    prefix:   /admin

# Admin Space /sales/admin/space
sandbox_admin_api_space:
    resource: "@SandboxSalesApiBundle/Controller/Space/AdminCommunityController.php"
    type:     annotation
    prefix:   /admin/space

# Admin Lease /sales/admin/leases
sandbox_admin_api_lease:
    resource: "@SandboxSalesApiBundle/Controller/Lease/AdminLeaseController.php"
    type:     annotation
    prefix:   /admin

# Admin Lease Bill /sales/admin/leases/bills
sandbox_admin_api_lease_bill:
    resource: "@SandboxSalesApiBundle/Controller/Lease/AdminLeaseBillController.php"
    type:     annotation
    prefix:   /admin

# Admin Product Appointments /sales/admin/products/appointments
sandbox_sales_admin_products_appointments:
    resource: "@SandboxSalesApiBundle/Controller/Product/AdminProductAppointmentController.php"
    type:     annotation
    prefix:   /admin/products

# Admin Log
sandbox_sales_admin_log:
    resource: "@SandboxSalesApiBundle/Controller/Log/AdminLogController.php"
    type:     annotation
    prefix:   /admin

# Admin Room Types /sales/admin/rooms/types
sandbox_sales_admin_room_types:
    resource: "@SandboxSalesApiBundle/Controller/Room/AdminRoomTypeController.php"
    type:     annotation
    prefix:   /admin

# Admin Withdraws /sales/admin/companies/{company_id}/withdraws
sandbox_sales_admin_companies_withdraws:
    resource: "@SandboxSalesApiBundle/Controller/Finance/AdminCompanyWithdrawalController.php"
    type:     annotation
    prefix:   /admin