landlord_client_api:
    resource: "@LandlordClientApiBundle/Resources/config/routing.yml"
    prefix:   /

sandbox_sales_api:
    resource: "@SandboxSalesApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /sales

sandbox_client_api:
    resource: "@SandboxClientApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /client

sandbox_admin_api:
    resource: "@SandboxAdminApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /admin

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

sandbox_api:
    resource: "@SandboxApiBundle/Resources/config/routing.yml"
    type: rest
    prefix:

sandbox_admin_shop_api:
    resource: "@SandboxAdminShopApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /shop