# FEEDS/feeds
sandbox_client_api_feed:
    resource: "@SandboxClientApiBundle/Controller/Feed/ClientFeedController.php"
    type:     annotation
    prefix:   /

sandbox_client_api_feed_like:
    resource: "@SandboxClientApiBundle/Controller/Feed/ClientFeedLikeController.php"
    type:     annotation
    prefix:   /

sandbox_client_api_feed_comment:
    resource: "@SandboxClientApiBundle/Controller/Feed/ClientFeedCommentController.php"
    type:     annotation
    prefix:   /

# COMPANIES Invitations /companies/invitations
sandbox_client_api_company_invitation:
    resource: "@SandboxClientApiBundle/Controller/Company/ClientCompanyInvitationController.php"
    type:     annotation
    prefix:   /companies

# COMPANIES /companies
sandbox_client_api_company:
    resource: "@SandboxClientApiBundle/Controller/Company/ClientCompanyController.php"
    type:     rest

# COMPANIES /companies/industries
sandbox_client_api_company_industry:
    resource: "@SandboxClientApiBundle/Controller/Company/ClientCompanyIndustryController.php"
    type:     rest
    parent:   sandbox_client_api_company

# COMPANIES /companies/portfolios
sandbox_client_api_company_portfolio:
    resource: "@SandboxClientApiBundle/Controller/Company/ClientCompanyPortfolioController.php"
    type:     rest
    parent:   sandbox_client_api_company

sandbox_client_api_company_member:
    resource: "@SandboxClientApiBundle/Controller/Company/ClientCompanyMemberController.php"
    type:     rest
    parent:   sandbox_client_api_company

# Profile /profile
sandbox_client_api_user_profile:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserProfileController.php"
    type:     annotation
    prefix:   /user

# Profile /profile
sandbox_client_api_user_profile_basic:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserBasicProfileController.php"
    type:     annotation
    prefix:   /user

# Profile /profile/education
sandbox_client_api_user_profile_education:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserEducationController.php"
    type:     annotation
    prefix:   /user

# Profile /profile/experience
sandbox_client_api_user_profile_experience:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserExperienceController.php"
    type:     annotation
    prefix:   /user

# Profile /profile/portfolio
sandbox_client_api_user_profile_portfolio:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserPortfolioController.php"
    type:     annotation
    prefix:   /user

# Profile /profile/hobby
sandbox_client_api_user_profile_hobby:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserHobbyController.php"
    type:     annotation
    prefix:   /user

# Client User Login /client/auth/login
sandbox_client_api_auth_login:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserLoginController.php"
    type:     annotation
    prefix:   /auth

# Client User Logout /client/auth/logout
sandbox_client_api_auth_logout:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserLogoutController.php"
    type:     annotation
    prefix:   /auth

# Bind email /email
sandbox_client_api_user_email_binding:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserEmailBindingController.php"
    type:     annotation
    prefix:   /user

# Bind phone /phone
sandbox_client_api_user_phone_binding:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserPhoneBindingController.php"
    type:     annotation
    prefix:   /user

# Registration /register
sandbox_client_api_user_registration:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserRegistrationController.php"
    type:     annotation
    prefix:   /user

# Password /password
sandbox_client_api_user_password:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserPasswordController.php"
    type:     annotation
    prefix:   /user

# Products /products/recommend
sandbox_client_api_product_recommend:
    resource: "@SandboxClientApiBundle/Controller/Product/ClientProductRecommendController.php"
    type:     annotation
    prefix:   /

# Products /products
sandbox_client_api_product:
    resource: "@SandboxClientApiBundle/Controller/Product/ClientProductController.php"
    type:     annotation
    prefix:   /

# Orders /orders
sandbox_client_api_order:
    resource: "@SandboxClientApiBundle/Controller/Order/ClientOrderController.php"
    type:     annotation
    prefix:   /

# Announcements /client/announcements
sandbox_client_api_announcements:
    resource: "@SandboxClientApiBundle/Controller/Announcement/ClientAnnouncementController.php"
    type:     annotation
    prefix:   /

# Payment /client/payment
sandbox_client_api_payment:
    resource: "@SandboxClientApiBundle/Controller/Payment/ClientPaymentController.php"
    type:     annotation
    prefix:   /

# TopUpOrders /topup
sandbox_client_api_topup_order:
    resource: "@SandboxClientApiBundle/Controller/Order/ClientTopUpOrderController.php"
    type:     annotation
    prefix:   /

# Buddy /buddies/requests
sandbox_client_api_buddy_request:
    resource: "@SandboxClientApiBundle/Controller/Buddy/ClientBuddyRequestController.php"
    type:     annotation
    prefix:   /buddies

# Buddy /buddies
sandbox_client_api_buddy:
    resource: "@SandboxClientApiBundle/Controller/Buddy/ClientBuddyController.php"
    type:     annotation
    prefix:   /

# Membere /members
sandbox_client_api_member:
    resource: "@SandboxClientApiBundle/Controller/Member/ClientMemberController.php"
    type:     annotation
    prefix:   /

# Client Token Auth /client/auth/me
sandbox_client_api_auth:
    resource: "@SandboxClientApiBundle/Controller/Auth/ClientAuthController.php"
    type:     annotation
    prefix:   /auth

# Door /client/doors
sandbox_client_api_doors:
    resource: "@SandboxClientApiBundle/Controller/Door/ClientDoorController.php"
    type:     annotation
    prefix:   /

# Account /account
sandbox_client_api_user_account:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserAccountController.php"
    type:     annotation
    prefix:   /user

# Food /food
sandbox_client_api_food:
    resource: "@SandboxClientApiBundle/Controller/Food/ClientFoodController.php"
    type:     annotation
    prefix:   /

# User Client /client/events/{id}/likes
sandbox_client_event_like:
    resource: "@SandboxClientApiBundle/Controller/Event/ClientEventLikeController.php"
    type:     annotation
    prefix:   /

# User Client /client/events/{id}/orders
sandbox_client_event_order:
    resource: "@SandboxClientApiBundle/Controller/Event/ClientEventOrderController.php"
    type:     annotation
    prefix:   /

# User Client /client/events
sandbox_client_event:
    resource: "@SandboxClientApiBundle/Controller/Event/ClientEventCommentController.php"
    type:     annotation
    prefix:   /

# Event Registration /client/events/{event_id}/registration
sandbox_client_api_event_registration:
    resource: "@SandboxClientApiBundle/Controller/Event/ClientEventRegistrationController.php"
    type:     annotation
    prefix:   /

# Event /client/events
sandbox_client_api_events:
    resource: "@SandboxClientApiBundle/Controller/Event/ClientEventController.php"
    type:     annotation
    prefix:   /

# ChatGroup /client/chatgroups
sandbox_client_api_chatgroup:
    resource: "@SandboxClientApiBundle/Controller/ChatGroup/ClientChatGroupController.php"
    type:     annotation
    prefix:   /

# ChatGroup members /client/chatgroups/{id}/members
sandbox_client_api_chatgroup_member:
    resource: "@SandboxClientApiBundle/Controller/ChatGroup/ClientChatGroupMemberController.php"
    type:     annotation
    prefix:   /

# FoodOrder /food
sandbox_client_api_food_orders:
    resource: "@SandboxClientApiBundle/Controller/Food/ClientFoodOrderController.php"
    type:     annotation
    prefix:   /

# Banner /banners
sandbox_client_api_banners:
    resource: "@SandboxClientApiBundle/Controller/Banner/ClientBannerController.php"
    type:     annotation
    prefix:   /

# News /client/news
sandbox_client_api_news:
    resource: "@SandboxClientApiBundle/Controller/News/ClientNewsController.php"
    type:     annotation
    prefix:   /

# Third Party Auth /client/thirdparty
sandbox_client_third_party:
    resource: "@SandboxClientApiBundle/Controller/ThirdParty/ClientThirdPartyController.php"
    type:     annotation
    prefix:   /thirdparty

# ShopOrder /client/shops/order
sandbox_client_api_shops_order:
    resource: "@SandboxClientApiBundle/Controller/Shop/ClientShopOrderController.php"
    type:     annotation
    prefix:   /

# Shop /client/shops
sandbox_client_api_shops:
    resource: "@SandboxClientApiBundle/Controller/Shop/ClientShopController.php"
    type:     annotation
    prefix:   /

# ShopMenu /client/shops/menu
sandbox_client_api_shops_menu:
    resource: "@SandboxClientApiBundle/Controller/Shop/ClientShopMenuController.php"
    type:     annotation
    prefix:   /

# ShopProduct /client/shops/product
sandbox_client_api_shops_product:
    resource: "@SandboxClientApiBundle/Controller/Shop/ClientShopProductController.php"
    type:     annotation
    prefix:   /

# Third Party Auth /client/thirdparty/oauth
sandbox_client_third_party_oauth:
    resource: "@SandboxClientApiBundle/Controller/ThirdParty/ClientThirdPartyOAuthController.php"
    type:     annotation
    prefix:   /thirdparty/oauth

# Third Party WeChat /client/thirdparty/wechat
sandbox_client_third_party_wechat:
    resource: "@SandboxClientApiBundle/Controller/ThirdParty/ClientThirdPartyWeChatController.php"
    type:     annotation
    prefix:   /thirdparty/wechat

# User Client /client/user/client
sandbox_client_user_client:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserClientController.php"
    type:     annotation
    prefix:   /user

# User Client /client/user/customer
sandbox_client_user_customer:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserCustomerController.php"
    type:     annotation
    prefix:   /user

# Profile Center /profile/myorders
sandbox_client_api_user_profile_my_orders:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserProfileMyOrdersController.php"
    type:     annotation
    prefix:   /user

# Advertising /advertising
sandbox_client_api_advertising:
    resource: "@SandboxClientApiBundle/Controller/Advertising/ClientAdvertisingController.php"
    type:     annotation
    prefix:   /

# Evaluation /evaluation
sandbox_client_api_evaluation:
    resource: "@SandboxClientApiBundle/Controller/Evaluation/ClientEvaluationController.php"
    type:     annotation
    prefix:   /

# UserFavorite  /user/favorites
sandbox_client_api_user_favorite:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserFavoriteController.php"
    type:     annotation
    prefix:   /user

# UserShare  /user/share
sandbox_client_api_user_share:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserShareController.php"
    type:     annotation
    prefix:   /user

# Lease /leases
sandbox_client_api_lease:
    resource: "@SandboxClientApiBundle/Controller/Lease/ClientLeaseController.php"
    type:     annotation
    prefix:   /

# Appointment Profile /appointment/profile
sandbox_client_api_user_appointment_profile:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserAppointmentProfileController.php"
    type:     annotation
    prefix:   /user/appointment

# ProductsAppointment /products/appointments
sandbox_client_api_product_appointment:
    resource: "@SandboxClientApiBundle/Controller/Product/ClientProductAppointmentController.php"
    type:     annotation
    prefix:   /

# Lease /leases/bills
sandbox_client_api_lease_bill:
    resource: "@SandboxClientApiBundle/Controller/Lease/ClientLeaseBillController.php"
    type:     annotation
    prefix:   /

# User Invoice Categories
sandbox_client_api_user_invoice_categories:
    resource: "@SandboxClientApiBundle/Controller/User/ClientUserSalesInvoiceCategoryController.php"
    type:     annotation
    prefix:   /

# User Customer Service
sandbox_client_api_customer_service:
    resource: "@SandboxClientApiBundle/Controller/CustomerService/ClientCustomerServiceController.php"
    type:     annotation
    prefix:   /

# User Membership Cards
sandbox_client_api_membership_card:
    resource: "@SandboxClientApiBundle/Controller/MembershipCard/ClientMembershipCardController.php"
    type:     annotation
    prefix:   /

# User Membership Orders
sandbox_client_api_membership_order:
    resource: "@SandboxClientApiBundle/Controller/MembershipCard/ClientMembershipOrderController.php"
    type:     annotation
    prefix:   /

# Bean
sandbox_client_api_bean:
    resource: "@SandboxClientApiBundle/Controller/Bean/ClientBeanController.php"
    type:     annotation
    prefix:   /

# Duiba
sandbox_client_api_duiba:
    resource: "@SandboxClientApiBundle/Controller/Duiba/ClientDuibaController.php"
    type:     annotation
    prefix:   /

sandbox_client_api_user_payment_check:
    resource: "@SandboxClientApiBundle/Controller/Payment/ClientUserPaymentCheckController.php"
    type:     annotation
    prefix:   /

sandbox_client_api_message_api:
    resource: "@SandboxClientApiBundle/Controller/Message/ClientMessageController.php"
    type:     annotation
    prefix:   /

sandbox_client_communities_api:
    resource: "@SandboxClientApiBundle/Controller/Community/ClientCommunityController.php"
    type:     annotation
    prefix:   /

#Reservation
sandbox_client_api_reservation:
    resource: "@SandboxClientApiBundle/Controller/Reservation/ClientReservationController.php"
    type:     annotation
    prefix:   /